services:
  - type: web
    name: car-sharing
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    autoDeployTrigger: off
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: docker
      - key: DB_HOST
        fromDatabase:
          name: car-sharing-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: car-sharing-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: car-sharing-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: car-sharing-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: car-sharing-db
          property: password
      - key: ADMIN_LOGIN
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: USER_INITIAL_CREDENTIAL
        sync: false

databases:
  - name: car-sharing-db
    plan: free
    region: frankfurt
    databaseName: car_sharing
    user: carsharing
    postgresMajorVersion: "16"
