server:
  port: ${SERVER_PORT:${PORT:8082}}

spring:
  profiles:
    default: ${SPRING_PROFILES_DEFAULT:local}

  application:
    name: carsharing

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/car_sharing?stringtype=unspecified}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  auth:
    admin:
      login: ${ADMIN_LOGIN:admin}
      password: ${ADMIN_PASSWORD:Admin123!}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
